server:
  port: 0

spring:
  application:
    name: business
  datasource:
    username: 'root'
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aicheck-mysql:3306/business?serverTimezone=UTC&characterEncoding=UTF-8
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    #    hibernate:
    #      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

jwt:
  secretKey: asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfa