server:
  port: 0

spring:
  application:
    name: alarm

  datasource:
    url: jdbc:mysql://aicheck-mysql:3306/alarm?serverTimezone=UTC&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: none
    database-platform: org.hibernate.dialect.MySQLDialect