server:
  port: 0

spring:
  application:
    name: alarm

  datasource:
    url: jdbc:mysql://aicheck-mysql:3306/alarm?serverTimezone=UTC&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092