server:
  port: 0

spring:
  application:
    name: alarm

  datasource:
    url: jdbc:mysql://aicheck-mysql:3306/alarm?serverTimezone=UTC&characterEncoding=UTF-8

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true