server:
  port: 0

spring:
  application:
    name: bank

  datasource:
    url: jdbc:mysql://aicheck-mysql:3306/bank?serverTimezone=UTC&characterEncoding=UTF-8
  jackson:
    property-naming-strategy: SNAKE_CASE

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true