server:
  port: 0

spring:
  application:
    name: bank

  datasource:
    url: jdbc:mysql://aicheck-mysql:3306/bank?serverTimezone=UTC&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: none
    database-platform: org.hibernate.dialect.MySQLDialect