server:
  port: 0

spring:
  application:
    name: business

  datasource:
    url: jdbc:mysql://aicheck-mysql:3306/business?serverTimezone=UTC&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  secretKey: ${TOKEN_SECRET}