server:
  port: 0

spring:
  application:
    name: business

  datasource:
    url: jdbc:mysql://aicheck-mysql:3306/business?serverTimezone=UTC&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: mail-redis
      port: 6379

jwt:
  secretKey: ${TOKEN_SECRET}