server:
  port: 0

spring:
  application:
    name: chatbot

  datasource:
    url: jdbc:mysql://aicheck-mysql:3306/chatbot?serverTimezone=UTC&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: chatbot-redis
      port: 6378