server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka/

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: alarm
          uri: lb://ALARM
          predicates:
            - Path=/alarm/**
          filters:
            - RewritePath=/alarm/(?<segment>/.*)?, /$\{segment}

        - id: bank
          uri: lb://BANK
          predicates:
            - Path=/bank/**
          filters:
            - RewritePath=/bank/(?<segment>/.*)?, /$\{segment}

        - id: batch
          uri: lb://BATCH
          predicates:
            - Path=/batch/**
          filters:
            - RewritePath=/batch/(?<segment>/.*)?, /$\{segment}

        - id: business
          uri: lb://BUSINESS
          predicates:
            - Path=/aicheck/**
          filters:
            - RewritePath=/aicheck/(?<segment>/.*)?, /$\{segment}

        - id: chatbot
          uri: lb://CHATBOT
          predicates:
            - Path=/chatbot/**
          filters:
            - RewritePath=/chatbot/(?<segment>/.*)?, /$\{segment}

#    globalcors:
#      add-to-simple-url-handler-mapping: true
#      corsConfigurations:
#        '[/**]':
#          allowedOrigins:
#            - "http://localhost:3000"
#            - "https://j12a603.p.ssafy.io"
#            - "http://j12a603.p.ssafy.io"
#            - "http://j12a603.p.ssafy.io:8080"
#          allowedMethods:
#            - GET
#            - POST
#            - PUT
#            - DELETE
#            - OPTIONS
#          allowedHeaders:
#            - "*"
#          allowCredentials: true

jwt:
  secretKey: ${TOKEN_SECRET}

trusted:
  origins:
    - "http://j12a603.p.ssafy.io"
    - "http://localhost:3000"
    - "http://localhost:8888"
    - "http://localhost:8761"